version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: signage-postgres
    environment:
      POSTGRES_DB: digital_signage
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: signage-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: